spring:
  application:
    name: rentals-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

jwt:
 private.key: classpath:app.key
 public.key: classpath:app.pub      